### ISSUE TITLE
(Smrithi) Display the dress page standardization

### ISSUE THREAD

**Issue by RajGollamudi** [sjasthi/abcd#26]
1. Follow the display model of http://www.projectabcd.com/modify_dress.php?id=1

2. Display current image, next to file name.  Showing the file name is useful to the programmer, but not to the end user

3. "Description" is a text area with 6 lines

4. "Did you know" is a text area with 2 lines

5. Ensure that the labels, fonts and colors are consistent with modify page.

6. (nice to have feature) Need to add a back button to go back to the earlier page

**Comment by RajGollamudi** [comment]
Font color inconsistent with other pages - Keep title as Gold as in Create/modify dress, center aligned, rest of the fonts are fine.
All the lines are left aligned without a left border to page
Need to add a back button to go back to the earlier page
Image needed while displaying dress

**Comment by sjasthi** [comment]
> 1. Follow the display model of http://www.projectabcd.com/modify_dress.php?id=1
> 2. Display current image, next to file name.  Showing the file name is useful to the programmer, but not to the end user
> 3. "Description" is a text area with 6 lines
> 4. "Did you know" is a text area with 2 lines
> 5. (nice to have feature) Need to add a back button to go back to the earlier page
