### ISSUE TITLE
(Nikhitha) Modify_Dress changes

### ISSUE THREAD

**Issue by RajGollamudi** [sjasthi/abcd#27]
1. Note and Status - add these two fields before image_url
2. Ensure that "status" retains the current value
------------>

1. Page title shows ABCD Master  instead of ProjectABCD

2. Did you Know? currently shows 1 after the ? "Did you know? 1"

3. Change the font color to match Display dress

4. Display current image, next to file name. and new image

5. "Description" is a text area with 6 lines

6. "Did you know" is a text area with 2 lines 

7. Many of the fields are OPTIONAL. You should not force the user to add value. Please check the database schema (I think only the name and id can not be NULL; rest of the fields can be null/empty)

**Comment by sjasthi** [comment]
provide the guidance message (just like create dialog) for category and type fields
